version: '3.9'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
    volumes:
      - .:/usr/src/app

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialmedia

  cache:
    image: redis:latest
    restart: always
    container_name: cache
    ports:
      - '6379:6379'
